### ISSUE TITLE
Add mutation range specification to config

### ISSUE THREAD

**Issue by MattWindsor91** [c4-project/c4t#105]
Something like:

```toml
[[Mutants]]
# specifying an inclusive range of values C4_MUTATION can take
first = 1
last  = 50

[[Mutants]]
# mutants 50 through 54 don't apply to the architecture
first = 55
last  = 60
```

Eventually it might be nice to specify mutants on a per-architecture basis, but that seems overly fancy for now.

Where this would go in the config depends on whether we're tracking mutations globally or per-machine (see #102)
