### ISSUE TITLE
Allow global mutant operator config

### ISSUE THREAD

**Issue by MattWindsor91** [c4-project/c4t#127]
Building on #126, another pattern is that many of the mutant operators work across machines; specifying them individually per machine is repetitive and error-prone.  As such, it would be nice to:

- have a global configuration of mutant ranges, using the same sort of syntax as present (and likely stored directly in the plan's root);
- allow range specifications as follows:

```toml
[[mutation.auto.ranges]]
  operator = "LT"
  start    = 108
  end      = 111
# ...
[[machines.foo.mutation.auto.ranges]]
  include = "LT"
```

This would just expand to the global definition for `LT`.
